#!/usr/bin/env bash

set -e

echo "-- chart/index --"

repo_index=${1}

echo "Getting current index from ${repo_index}"
curl -f http://pandaria-releases.cnrancher.com/server-charts/${repo_index}/index.yaml -o /tmp/index.yaml

helm repo index --merge /tmp/index.yaml ../bin/chart/${repo_index}
