---
kind: pipeline
name: default-linux-amd64
platform:
  os: linux
  arch: amd64
steps:
- name: pre-check
  pull: default
  image: rancher/dapper:v0.5.2
  environment:
    http_proxy:
      from_secret: http_proxy
  commands:
  - dapper -f Dockerfile-pandaria.dapper pre-check
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request

- name: build
  pull: default
  image: rancher/dapper:v0.5.2
  environment:
    OAUTH_TOKEN:
      from_secret: github_token
    GOPROXY:
      from_secret: go_proxy
    http_proxy:
      from_secret: http_proxy
    SKIP_TESTS: 1
  commands:
  - apk add git make curl go=1.13.13-r0 bzr
  - make -f Makefile.pandaria
  privileged: true
  volumes:
  - name: docker
    path: /var/run/docker.sock
  privileged: true
  when:
    event:
    - push
    - pull_request

- name: stage-binaries
  image: rancher/dapper:v0.5.2
  commands:
  - "cp -r ./bin/* ./package/"
  when:
    event:
    - push

- name: docker-publish-head
  pull: default
  image: plugins/docker:18.09
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=v2.4-${DRONE_BUILD_NUMBER}-head-f5
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile.pandaria
    tag: v2.4-head-f5
    password:
      from_secret: docker_password
    repo: cnrancher/rancher
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/release/v2.4-ent-f5"
    event:
    - push

- name: docker-publish-head-agent
  pull: default
  image: plugins/docker:18.09
  settings:
    build_args:
    - ARCH=amd64
    - VERSION=v2.4-${DRONE_BUILD_NUMBER}-head-f5
    context: package/
    custom_dns: 1.1.1.1
    dockerfile: package/Dockerfile-pandaria.agent
    tag: v2.4-${DRONE_BUILD_NUMBER}-head-f5
    password:
      from_secret: docker_password
    repo: cnrancher/rancher-agent
    username:
      from_secret: docker_username
  when:
    ref:
      include:
      - "refs/heads/release/v2.4-ent-f5"
    event:
    - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64

trigger:
  event:
    exclude:
    - promote

...

