#!/bin/bash
set -e

cd $(dirname $0)/..

REQUIRE="
github.com/vgough/grpc-proxy@v0.0.0-20191207203309-13d1aa04a5a6
github.com/aliyun/alibaba-cloud-sdk-go@v1.61.27
gopkg.in/cas.v2@v2.2.0
github.com/prometheus/prometheus@v2.18.2+incompatible
github.com/rancher/prometheus-auth/pkg/data@v0.2.0
github.com/rancher/prometheus-auth/pkg/prom@v0.2.0
github.com/tidwall/gjson@v1.6.1
"

REPLACE="
github.com/Azure/azure-sdk-for-go=github.com/Azure/azure-sdk-for-go@v36.2.0+incompatible
github.com/rancher/types=github.com/cnrancher/pandaria-types@v0.0.0-20201217015310-765e4046ce2c
github.com/rancher/kontainer-engine=github.com/cnrancher/kontainer-engine@v0.0.4-dev.0.20201112072054-6d9f578df4cc
github.com/rancher/prometheus-auth/pkg/data=github.com/cnrancher/prometheus-auth/pkg/data@v0.0.0-20201013075525-c015fa82fdd7
github.com/rancher/prometheus-auth/pkg/prom=github.com/cnrancher/prometheus-auth/pkg/prom@v0.0.0-20201013075525-c015fa82fdd7
github.com/prometheus/prometheus=github.com/prometheus/prometheus@v0.0.0-20200626085723-c448ada63d83
github.com/satori/go.uuid=github.com/satori/go.uuid@v1.2.0
github.com/segmentio/kafka-go=github.com/segmentio/kafka-go@v0.0.0-20190411192201-218fd49cff39
github.com/rancher/norman=github.com/cnrancher/pandaria-norman@v0.0.0-20201109020557-c821f2673c25
github.com/rancher/steve=github.com/cnrancher/steve@v0.0.0-20201112070150-5880c657c321
"

# https://golang.org/cmd/go/#hdr-Edit_go_mod_from_tools_or_scripts

for m in $REQUIRE; do
   go mod edit -require $m
done

for m in $REPLACE; do
   go mod edit -replace $m
done

if [ "$OAUTH_TOKEN" != "" ]; then
   git config --global url."https://${OAUTH_TOKEN}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
fi

GOPRIVATE="github.com/cnrancher" go mod vendor
